version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE=streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
    networks:
      - skin-lesion-net

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - SERVICE=api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    networks:
      - skin-lesion-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - skin-lesion-net

networks:
  skin-lesion-net:
    driver: bridge